apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: team-b-env-crb 
subjects:
- kind: ServiceAccount
  name: vc-team-b-env
  namespace: team-b-env
roleRef: # referring to your ClusterRole
  kind: ClusterRole
  name: dapr-operator-admin 
  apiGroup: rbac.authorization.k8s.io
