apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp-dapr
spec:
  selector:
    matchLabels:
      app: webapp-dapr
  template:
    metadata:
      annotations:
        dapr.io/app-id: webapp-dapr
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "9099"
      labels:
        app: webapp-dapr
    spec:
      containers:
      - name: webapp-dapr
        image: docker.io/salaboy/webapp-5dd817b6438eb2b7aec9bd0d6b49d12b@sha256:827e3a56a2aaf5237919cb8963388344718af2cb4cb21a6997ee9a14a2c83846
        ports:
        - containerPort: 8080